### ISSUE TITLE
Upgrade jest-speck-plugin to handle usage files

### ISSUE THREAD

**Issue by pvienneau** [mb3online/jest-speck-plugin#13]
At the moment, the generated spec files still generate the JSX tags inline, through the classname. We will need to update this to generate a generic import to a usage file and push this through the first 3 tests.

**Comment by ericadamski** [comment]
@pvienneau what do you mean here?

**Comment by pvienneau** [comment]
@ericadamski We are pulling our components into our `spec` files, which should be reflected in the spec files generated by Speck.

**Comment by ericadamski** [comment]
@pvienneau maybe a better question is, does speck have enough context to achieve this reliably?

**Comment by pvienneau** [comment]
@ericadamski Not `speck`, but `jest-speck-plugin` is able to make safe assumption on Particle's import/implementation approaches. What are your concerns on this?

**Comment by ericadamski** [comment]
@pvienneau I just don't think I fully grasp what it is you are trying to do :p no concerns
